name: docker-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  DOCKER_BUILD_AND_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build -t woochanlee/java-project-frame-admin .

      - name: publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: woochanlee/java-project-frame-admin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
